baseurl = "https://fervent-goodall-2a0131.netlify.com/"
title = "The study of the household"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Andrew MacDonald"
disqusShortname = "thestudyofthehousehold"
googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#relativeurls = false

[Author]
    name = "Andrew MacDonald"
    profile = "https://aammd.info"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "The Study of the Household"
    description = "How the science of ecology connects to everything"
    github = "https://github.com/aammd"
    gitlab = ""
    linkedin = "https://linkedin.com/in/andrew-macdonald-76649474/"
    gplus = ""
    twitter = "https://twitter.com/polesasunder"
    stackoverflow = "https://stackoverflow.com/users/1727133/andrewmacdonald"
    email = "a.a.m.macdonald@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon / 2 Jan 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = ":filename/"
#
#[[menu.main]]
#    name = "Blog"
#    url = "/"
#    weight = 1
#
#[[menu.main]]
#    name = "Projects"
#    url = "/project/"
#    weight = 2

#[[menu.main]]
#    name = "Contact"
#    url = "/page/contact/"
#    weight = 3
#
#[[menu.main]]
#    name = "About"
#    url = "/page/about/"
#    weight = 4
